#ifndef DOWNLOAD_REPLAYS
#define DOWNLOAD_REPLAYS 1
#endif

#ifndef LOGIN_AUTOMATICALLY
#define LOGIN_AUTOMATICALLY 1
#endif

#ifndef JOIN_ROOM_AUTOMATICALLY
#define JOIN_ROOM_AUTOMATICALLY 1
#endif

#ifndef _SSL
#define _SSL 1
#endif

//SSL HAS DRIVEN ME MAD PLEASE SOMEONE FIX MY SSL
